#!/usr/bin/env python3
"""
Compile sunglasses/mechanisms.py -> src/mechanisms.js.

Same job as compile_patterns.py, same regex translator (imported, not
reimplemented) — hand-porting these by eye is how the two engines drift, and
parity is the product promise. Run this whenever mechanisms.py changes, then
run engine_parity.py and require 0 disagreements.

    python3 compile_mechanisms.py
"""
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path.home() / "sunglasses-dev" / "glasses"))

from sunglasses.mechanisms import MECHANISM_PATTERNS  # noqa: E402
from sunglasses.engine import SunglassesEngine  # noqa: E402

from compile_patterns import convert, node_validate  # noqa: E402

OUT = Path(__file__).parent / "src" / "mechanisms.js"


def main():
    compiled = []
    flat = []
    owners = []

    for p in MECHANISM_PATTERNS:
        entry = {
            "id": p["id"],
            "name": p["name"],
            "category": p["category"],
            "severity": p["severity"],
            "channel": p.get("channel", []),
            "keywords": [],
            "negation_immune": bool(p.get("negation_immune")),
            "regex": [],
            "description": p.get("description", ""),
        }
        for rx in p.get("regex", []) or []:
            src, fl = convert(rx)
            # Mode scheme (v0.3.3) — mechanisms are \b-led shape regexes, so
            # they compile to plain/windowed; the guarded mode is carrier-only.
            entry["regex"].append({
                "source": src,
                "flags": fl,
                "mode": "windowed" if SunglassesEngine._is_anchored(rx) else "plain",
            })
        compiled.append(entry)

    for idx, entry in enumerate(compiled):
        for ri, r in enumerate(entry["regex"]):
            flat.append({"id": entry["id"], "source": r["source"], "flags": r["flags"]})
            owners.append((idx, ri))

    errors = node_validate(flat)
    bad = [(flat[i]["id"], e) for i, e in enumerate(errors) if e]
    if bad:
        for mid, err in bad:
            print(f"FAIL {mid}: {err}", file=sys.stderr)
        sys.exit(1)

    body = ",\n  ".join(json.dumps(e) for e in compiled)
    OUT.write_text(
        "// AUTO-GENERATED by compile_mechanisms.py — DO NOT EDIT\n"
        f"// Source: sunglasses/mechanisms.py ({len(compiled)} mechanisms)\n"
        "// Mechanisms match attack SHAPE, not wording. They are a FALLBACK layer:\n"
        "// engine.js suppresses a mechanism when a carrier of the same category\n"
        "// already fired at >= severity. Counted separately from PATTERNS.\n"
        f"export const MECHANISMS = [\n  {body},\n];\n"
    )
    print(f"mechanisms compiled : {len(compiled)}")
    print(f"regexes validated   : {len(flat)} (0 errors)")
    print(f"written             : {OUT}")


if __name__ == "__main__":
    main()
